///|
pub extend Arguments with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Arguments with Eq::{not_equal, equal}

///|
pub extend Arguments with ToJson::{to_json}

///|
pub extend BuildComparison with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend BuildComparison with Eq::{not_equal, equal}

///|
pub extend BuildComparison with ToJson::{to_json}

///|
pub extend BuildEdge with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend BuildEdge with Eq::{not_equal, equal}

///|
pub extend BuildEdge with ToJson::{to_json}

///|
pub extend BuildImpact with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend BuildImpact with Eq::{not_equal, equal}

///|
pub extend BuildImpact with ToJson::{to_json}

///|
pub extend BuildUncertainty with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend BuildUncertainty with Eq::{not_equal, equal}

///|
pub extend BuildUncertainty with ToJson::{to_json}

///|
pub extend ContextChange with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ContextChange with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend ContextChange with Eq::{not_equal, equal}

///|
pub extend ContextChange with ToJson::{to_json}

///|
pub extend ContextEntry with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ContextEntry with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend ContextEntry with Eq::{not_equal, equal}

///|
pub extend ContextEntry with ToJson::{to_json}

///|
pub extend ContextFileImpact with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ContextFileImpact with Eq::{not_equal, equal}

///|
pub extend ContextFileImpact with ToJson::{to_json}

///|
pub extend ContextInput with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ContextInput with Eq::{not_equal, equal}

///|
pub extend ContextInput with ToJson::{to_json}

///|
pub extend ContextPlan with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ContextPlan with Eq::{not_equal, equal}

///|
pub extend ContextPlan with ToJson::{to_json}

///|
pub extend Diagnostic with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Diagnostic with Eq::{not_equal, equal}

///|
pub extend Diagnostic with ToJson::{to_json}

///|
pub extend Expansion with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Expansion with Eq::{not_equal, equal}

///|
pub extend Expansion with ToJson::{to_json}

///|
pub extend HereDoc with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend HereDoc with Eq::{not_equal, equal}

///|
pub extend HereDoc with ToJson::{to_json}

///|
pub extend Instruction with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Instruction with Eq::{not_equal, equal}

///|
pub extend Instruction with ToJson::{to_json}

///|
pub extend ParseError with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ShellToken with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ShellToken with Eq::{not_equal, equal}

///|
pub extend ShellToken with ToJson::{to_json}

///|
pub extend SourceComparison with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SourceComparison with Eq::{not_equal, equal}

///|
pub extend SourceComparison with ToJson::{to_json}

///|
pub extend Stage with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Stage with Eq::{not_equal, equal}

///|
pub extend Stage with ToJson::{to_json}

///|
pub extend TargetImpact with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend TargetImpact with Eq::{not_equal, equal}

///|
pub extend TargetImpact with ToJson::{to_json}

///|
pub extend VariableScope with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend VariableScope with Eq::{not_equal, equal}

///|
pub extend VariableScope with ToJson::{to_json}
